"""add individual chats table

Revision ID: 640293a12ead
Revises: 234f98d6c1a4
Create Date: 2025-09-17 11:19:22.133414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640293a12ead'
down_revision = '234f98d6c1a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('individual_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('other_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['other_user_id'], ['users.id'], name=op.f('fk_individual_chats_other_user_id_users')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_individual_chats_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'other_user_id', name='unique_chat_pair')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('individual_chats')
    # ### end Alembic commands ###
